<?php

echo '<h2 id="">Profil</h2>
<div>

Sous l\'onglet Insertion, les galeries incluent des éléments conçus pour être coordonnés avec l\'aspect général de votre document. Vous pouvez utiliser ces galeries pour insérer des tables, des en-têtes, des pieds de page, des listes, des pages de garde et tout autre bloc de construction d\'un document. Lorsque vous créez des images, des graphiques ou des diagrammes, ils sont également coordonnés avec l\'aspect de votre document actuel. Vous pouvez facilement modifier la mise en forme du texte sélectionné dans le document en choisissant une apparence pour celui-ci dans la galerie Styles rapides sous l\'onglet Écriture. Vous pouvez également mettre en forme le texte directement en utilisant les autres contrôles de l\'onglet Écriture.
La plupart des contrôles permettent d\'utiliser le thème actuel ou de définir une mise en forme directement. Pour modifier l\'aspect général de votre document, choisissez les nouveaux éléments dans le groupe Thèmes sous l\'onglet Mise en page. Pour modifier les choix de présentation disponibles dans la galerie de styles rapides, utilisez la commande de modification du style rapide actif. Les galeries Thèmes et Styles rapides fournissent des commandes de réinitialisation qui vous permettent de toujours rétablir l\'aspect de votre document conformément à l\'original contenu dans le modèle actif. Sous l\'onglet Insertion, les galeries incluent des éléments conçus pour être coordonnés avec l\'aspect général de votre document.
<br/></div><div>Vous pouvez utiliser ces galeries pour insérer des tables, des en-têtes, des pieds de page, des listes, des pages de garde et tout autre bloc de construction d\'un document. Lorsque vous créez des images, des graphiques ou des diagrammes, ils sont également coordonnés avec l\'aspect de votre document actuel. Vous pouvez facilement modifier la mise en forme du texte sélectionné dans le document en choisissant une apparence pour celui-ci dans la galerie Styles rapides sous l\'onglet Écriture. Vous pouvez également mettre en forme le texte directement en utilisant les autres contrôles de l\'onglet Écriture. La plupart des contrôles permettent d\'utiliser le thème actuel ou de définir une mise en forme directement.
Pour modifier l\'aspect général de votre document, choisissez les nouveaux éléments dans le groupe Thèmes sous l\'onglet Mise en page. Pour modifier les choix de présentation disponibles dans la galerie de styles rapides, utilisez la commande de modification du style rapide actif. Les galeries Thèmes et Styles rapides fournissent des commandes de réinitialisation qui vous permettent de toujours rétablir l\'aspect de votre document conformément à l\'original contenu dans le modèle actif. Sous l\'onglet Insertion, les galeries incluent des éléments conçus pour être coordonnés avec l\'aspect général de votre document. Vous pouvez utiliser ces galeries pour insérer des tables, des en-têtes, des pieds de page, des listes, des pages de garde et tout autre bloc de construction d\'un document.
<br/></div><div>Lorsque vous créez des images, des graphiques ou des diagrammes, ils sont également coordonnés avec l\'aspect de votre document actuel. Vous pouvez facilement modifier la mise en forme du texte sélectionné dans le document en choisissant une apparence pour celui-ci dans la galerie Styles rapides sous l\'onglet Écriture. Vous pouvez également mettre en forme le texte directement en utilisant les autres contrôles de l\'onglet Écriture. La plupart des contrôles permettent d\'utiliser le thème actuel ou de définir une mise en forme directement. Pour modifier l\'aspect général de votre document, choisissez les nouveaux éléments dans le groupe Thèmes sous l\'onglet Mise en page.
Pour modifier les choix de présentation disponibles dans la galerie de styles rapides, utilisez la commande de modification du style rapide actif. Les galeries Thèmes et Styles rapides fournissent des commandes de réinitialisation qui vous permettent de toujours rétablir l\'aspect de votre document conformément à l\'original contenu dans le modèle actif. Sous l\'onglet Insertion, les galeries incluent des éléments conçus pour être coordonnés avec l\'aspect général de votre document. Vous pouvez utiliser ces galeries pour insérer des tables, des en-têtes, des pieds de page, des listes, des pages de garde et tout autre bloc de construction d\'un document. Lorsque vous créez des images, des graphiques ou des diagrammes, ils sont également coordonnés avec l\'aspect de votre document actuel.
<br/></div><div>Vous pouvez facilement modifier la mise en forme du texte sélectionné dans le document en choisissant une apparence pour celui-ci dans la galerie Styles rapides sous l\'onglet Écriture. Vous pouvez également mettre en forme le texte directement en utilisant les autres contrôles de l\'onglet Écriture. La plupart des contrôles permettent d\'utiliser le thème actuel ou de définir une mise en forme directement. Pour modifier l\'aspect général de votre document, choisissez les nouveaux éléments dans le groupe Thèmes sous l\'onglet Mise en page. Pour modifier les choix de présentation disponibles dans la galerie de styles rapides, utilisez la commande de modification du style rapide actif.
Les galeries Thèmes et Styles rapides fournissent des commandes de réinitialisation qui vous permettent de toujours rétablir l\'aspect de votre document conformément à l\'original contenu dans le modèle actif. Sous l\'onglet Insertion, les galeries incluent des éléments conçus pour être coordonnés avec l\'aspect général de votre document. Vous pouvez utiliser ces galeries pour insérer des tables, des en-têtes, des pieds de page, des listes, des pages de garde et tout autre bloc de construction d\'un document. Lorsque vous créez des images, des graphiques ou des diagrammes, ils sont également coordonnés avec l\'aspect de votre document actuel. Vous pouvez facilement modifier la mise en forme du texte sélectionné dans le document en choisissant une apparence pour celui-ci dans la galerie Styles rapides sous l\'onglet Écriture.
<br/></div><div>Vous pouvez également mettre en forme le texte directement en utilisant les autres contrôles de l\'onglet Écriture. La plupart des contrôles permettent d\'utiliser le thème actuel ou de définir une mise en forme directement. Pour modifier l\'aspect général de votre document, choisissez les nouveaux éléments dans le groupe Thèmes sous l\'onglet Mise en page. Pour modifier les choix de présentation disponibles dans la galerie de styles rapides, utilisez la commande de modification du style rapide actif. Les galeries Thèmes et Styles rapides fournissent des commandes de réinitialisation qui vous permettent de toujours rétablir l\'aspect de votre document conformément à l\'original contenu dans le modèle actif.
Sous l\'onglet Insertion, les galeries incluent des éléments conçus pour être coordonnés avec l\'aspect général de votre document. Vous pouvez utiliser ces galeries pour insérer des tables, des en-têtes, des pieds de page, des listes, des pages de garde et tout autre bloc de construction d\'un document. Lorsque vous créez des images, des graphiques ou des diagrammes, ils sont également coordonnés avec l\'aspect de votre document actuel. Vous pouvez facilement modifier la mise en forme du texte sélectionné dans le document en choisissant une apparence pour celui-ci dans la galerie Styles rapides sous l\'onglet Écriture. Vous pouvez également mettre en forme le texte directement en utilisant les autres contrôles de l\'onglet Écriture.

</div>
<div>Made in InTeamITII ;D</div>

';

?>
